### ISSUE TITLE
Lab 3

### ISSUE THREAD

**Issue by Raiden-Makoto** [qiskit-community/ibm-quantum-challenge-2024#19]
If there are only 2 graded exercises for the third lab, why does the challenge website say "You have completed 2 out of 6 questions?"

**Comment by AIdjis** [comment]
There is another part of Lab 3 that will be released on the 10th of this month.

**Comment by Raiden-Makoto** [comment]
why make it so confusing then? it doesn't say this anywhere

**Comment by ashishpatel26** [comment]
The challenge website incorrectly reports the number of completed questions. There are only two graded exercises for the third lab, but the website incorrectly states that two out of six questions have been completed. This discrepancy is likely due to an error in the website's tracking mechanism.
![image](https://github.com/qiskit-community/ibm-quantum-challenge-2024/assets/3095771/4745515c-3cd5-4702-98c4-ad37bb2b3deb)

**Comment by ashishpatel26** [comment]
> here is another part of Lab 3 that will be released on the 10th of this month

Is there mentioned anywhere?
